# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  LEP_joint:
    has_velocity_limits: true
    max_velocity: 10.47
    has_acceleration_limits: true
    max_acceleration: 1.0
  LGRF_joint:
    has_velocity_limits: true
    max_velocity: 0.29999999999999999
    has_acceleration_limits: true
    max_acceleration: 1.0
  LSP_joint:
    has_velocity_limits: true
    max_velocity: 10.47
    has_acceleration_limits: true
    max_acceleration: 1.0
  LSR_joint:
    has_velocity_limits: true
    max_velocity: 10.47
    has_acceleration_limits: true
    max_acceleration: 1.0
  LSY_joint:
    has_velocity_limits: true
    max_velocity: 10.47
    has_acceleration_limits: true
    max_acceleration: 1.0
  LWP_joint:
    has_velocity_limits: true
    max_velocity: 10.47
    has_acceleration_limits: true
    max_acceleration: 1.0
  LWR_joint:
    has_velocity_limits: true
    max_velocity: 10.47
    has_acceleration_limits: true
    max_acceleration: 1.0
  LWY_joint:
    has_velocity_limits: true
    max_velocity: 10.47
    has_acceleration_limits: true
    max_acceleration: 1.0
  REP_joint:
    has_velocity_limits: true
    max_velocity: 10.47
    has_acceleration_limits: true
    max_acceleration: 1.0
  RGRF_joint:
    has_velocity_limits: true
    max_velocity: 0.29999999999999999
    has_acceleration_limits: true
    max_acceleration: 1.0
  RSP_joint:
    has_velocity_limits: true
    max_velocity: 10.47
    has_acceleration_limits: true
    max_acceleration: 1.0
  RSR_joint:
    has_velocity_limits: true
    max_velocity: 10.47
    has_acceleration_limits: true
    max_acceleration: 1.0
  RSY_joint:
    has_velocity_limits: true
    max_velocity: 10.47
    has_acceleration_limits: true
    max_acceleration: 1.0
  RWP_joint:
    has_velocity_limits: true
    max_velocity: 10.47
    has_acceleration_limits: true
    max_acceleration: 1.0
  RWR_joint:
    has_velocity_limits: true
    max_velocity: 10.47
    has_acceleration_limits: true
    max_acceleration: 1.0
  RWY_joint:
    has_velocity_limits: true
    max_velocity: 10.47
    has_acceleration_limits: true
    max_acceleration: 1.0
