# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_trajectory_controller
    - right_arm_trajectory_controller
    - left_gripper_controller
    - right_gripper_controller

  left_arm_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - LSP_joint
      - LSY_joint
      - LSR_joint
      - LEP_joint
      - LWR_joint
      - LWP_joint
      - LWY_joint
  right_arm_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - RSP_joint
      - RSY_joint
      - RSR_joint
      - REP_joint
      - RWR_joint
      - RWP_joint
      - RWY_joint
  left_gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory    
    joints:
      - LGRF_joint
  right_gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory    
    joints:
      - RGRF_joint
